# Generated by Django 5.0.6 on 2024-06-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "faunatrack",
            "0002_remove_espece_nom_commun_espece_nom_espece_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="espece",
            name="nom",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
