# Generated by Django 5.0.6 on 2024-06-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faunatrack", "0003_alter_espece_nom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projet",
            name="slug",
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
