# Generated by Django 5.0.6 on 2024-06-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faunatrack", "0004_alter_projet_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projet",
            name="observations",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="projets",
                to="faunatrack.observation",
            ),
        ),
    ]
