# Generated by Django 5.0.6 on 2024-06-20 10:19

import django.core.validators
import faunatrack.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faunatrack", "0005_alter_projet_observations"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="lattitude",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                max_digits=9,
                validators=[faunatrack.validators.validate_latitude],
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                max_digits=9,
                validators=[faunatrack.validators.validate_longitude],
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="quantite",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
