# Generated by Django 5.0.6 on 2024-06-20 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faunatrack", "0007_alter_scientifique_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
